version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/app
hooks:
  AfterInstall:
    - location: scripts/build_server.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/run_server.sh
      timeout: 300
      runas: root
